<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Giftcard
 * @version    1.0.9
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><div class="customer-giftcard">
    <?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
    <?php if(Mage::registry('current_giftcard')): ?>
        <div id="aw-giftcard-info-block">
            <div class="fieldset">
                <h2 class="legend"><?php echo $this->__('Gift Card Information');?></h2>
                <table>
                    <tr>
                        <td class="label">
                            <?php echo $this->__('Code');?>
                        </td>
                        <td>
                            <strong class="giftcard-code">
                                <?php echo Mage::registry('current_giftcard')->getCode();?>
                            </strong>
                        </td>
                    </tr>
                    <tr>
                        <td class="label">
                            <?php echo $this->__('Active');?>
                        </td>
                        <td>
                            <strong class="giftcard-status">
                                <?php echo Mage::getModel('aw_giftcard/source_product_attribute_option_yesno')->getOptionText(Mage::registry('current_giftcard')->getStatus());?>
                            </strong>
                        </td>
                    </tr>
                    <tr>
                        <td class="label">
                            <?php echo $this->__('Status');?>
                        </td>
                        <td>
                            <strong class="giftcard-state">
                                <?php echo Mage::getModel('aw_giftcard/source_giftcard_status')->getOptionByValue(Mage::registry('current_giftcard')->getState());?>
                            </strong>
                        </td>
                    </tr>
                    <tr>
                        <td class="label">
                            <?php echo $this->__('Balance');?>
                        </td>
                        <td>
                            <span class="price">
                                <?php echo Mage::helper('core')->currency(Mage::registry('current_giftcard')->getBalance());?>
                            </span>
                        </td>
                    </tr>
                    <?php if (Mage::registry('current_giftcard')->getExpireAt()): ?>
                    <tr>
                        <td class="label">
                            <?php echo $this->__('Expires');?>
                        </td>
                        <td>
                            <strong>
                                <?php echo $this->formatDate(Mage::registry('current_giftcard')->getExpireAt(), 'short')?>
                            </strong>
                        </td>
                    </tr>
                    <?php endif;?>
                </table>
            </div>
        </div>
    <?php endif;?>
    <form id="aw_giftcard-form" action="<?php echo $this->getFormUrl(); ?>" method="post" class="form">
        <div class="form__field">
            <p class="form__field form__field--required">
                <label for="giftcard_code" class="form__label form__label--required"><?php echo $this->__('Enter gift card code') ?></label>
                <input type="text" id="giftcard_code" name="giftcard_code" class="required-entry form__textfield textfield" value="<?php echo $this->getCurrentGiftcard(); ?>" />
            </p>
            <p class="form__submit-wrapper">
                <span class="required">
                    <?php echo $this->__('Required Fields') ?>
                </span>
                <button class="button check-gc-status" id="check-gc-status" type="button" onclick="AwGiftcardForm.submit(this)" value="<?php echo $this->__('Check status and balance') ?>"><?php echo $this->__('Check status and balance') ?></button>
            </p>
        </div>
    </form>
    <script type="text/javascript">
        var AwGiftcardForm = new VarienForm('aw_giftcard-form');
    </script>
</div>