<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Giftcard
 * @version    1.0.9
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php
$giftcard = Mage::getSingleton('checkout/session')->getCurrentGiftCard();
Mage::getSingleton('checkout/session')->setCurrentGiftCard(null);
?>
<div class="discount aw_giftcard">
    <?php if ($giftcard):?>
    <div id="aw-giftcard-info-block" class="gift-card-info">
        <div class="gift-card-info-item">
            <span class="title"><?php echo $this->__("Code:"); ?></span>
            <span class="value"><?php echo $this->__("%s", $giftcard->getCode());?></span>
        </div>
        <div class="gift-card-info-item">
            <span class="title"><?php echo $this->__("Active:"); ?></span>
            <span class="value"><?php echo $this->__("%s", Mage::getModel('aw_giftcard/source_product_attribute_option_yesno')->getOptionText($giftcard->getStatus())); ?></span>
        </div>
        <div class="gift-card-info-item">
            <span class="title"><?php echo $this->__("Status:"); ?></span>
            <span class="value"><?php echo $this->__("%s", Mage::getModel('aw_giftcard/source_giftcard_status')->getOptionByValue($giftcard->getState()));?></span>
        </div>
        <div class="gift-card-info-item">
            <span class="title"><?php echo $this->__("Balance:"); ?></span>
            <span class="value"><?php echo $this->__("%s", Mage::helper('core')->currency($giftcard->getBalance()));?></span>
        </div>
        <?php if ($giftcard->getExpireAt()): ?>
            <div class="gift-card-info-item">
                <span class="title"><?php echo $this->__("Expires:"); ?></span>
                <span class="value"><?php echo $this->__("%s", $this->formatDate($giftcard->getExpireAt(), 'short'));?></span>
            </div>
        <?php endif;?>
    </div>
    <div style="clear:both"></div>
    <?php endif;?>
    <form id="aw_giftcard-form" class="form" action="<?php echo $this->getFormUrl();?>" method="post">
        <label for="giftcard_code" class="discount__field-label"><?php echo $this->__('Enter your gift card code') ?></label>
        <input class="required-entry discount__textfield textfield" id="giftcard_code" name="giftcard_code" value="" />
        <p class="discount__submit-wrapper">
            <button class="discount__submit js-apply-discount" onclick="window.giftcardForm.submit()" type="button" value="<?php echo $this->__('Add Gift Card') ?>">
                <span><span><?php echo $this->__('Add Gift Card') ?></span></span>
            </button>
            <button class="discount__submit js-apply-discount" onclick="window.awGiftcardCheckStatus()" type="button" value="<?php echo $this->__('Check Gift Card status') ?>">
                <span><span><?php echo $this->__('Check Gift Card status') ?></span></span>
            </button>
            <input id="status_input" type="hidden" value="0" name="status_flag">
        </p>
    </form>

    <script type="text/javascript">
        window.giftcardForm = new VarienForm('aw_giftcard-form');
        window.awGiftcardCheckStatus = function () {
            $('status_input').value = 1;
            window.giftcardForm.submit();
            return true;
        }
    </script>
</div>