<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Giftcard
 * @version    1.0.9
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><div class="discount__field aw_giftcard">
    <h2><?php echo $this->__('Gift Cards') ?></h2>
    <form id="aw_giftcard-form" class="form" action="<?php echo $this->getFormUrl();?>" method="post">
        <label for="giftcard_code" class="discount__field-label"><?php echo $this->__('Enter your gift card code') ?></label>
        <input class="required-entry discount__textfield textfield" id="giftcard_code" name="giftcard_code" value="" />
        <p class="discount__submit-wrapper">
            <button class="discount__submit js-apply-discount" onclick="window.giftcardForm.submit()" type="button" value="<?php echo $this->__('Add Gift Card') ?>">
                <span><span><?php echo $this->__('Add Gift Card') ?></span></span>
            </button>
            <button class="discount__submit js-apply-discount" onclick="awGiftcardCheckStatus()" type="button" value="<?php echo $this->__('Check Gift Card status') ?>">
                <span><span><?php echo $this->__('Check Gift Card status') ?></span></span>
            </button>
        </p>
    </form>

    <script type="text/javascript">
        window.giftcardForm = new VarienForm('aw_giftcard-form');
        var awGiftcardCheckStatus = function () {
            $$('.loader').first().setStyle({zIndex: "101"}).show();
            new Ajax.Request(<?php echo Zend_Json::encode($this->getUrl("aw_giftcard/card/checkmobileajax"));?>, {
                parameters: {giftcard_code: $('giftcard_code').getValue()},
                onSuccess: function(transport) {
                    if (!transport.responseText) {
                        return;
                    }
                    $$('.gift-card-info').each(function(el){
                        el.remove();
                    });
                    var container = new Element('div');
                    container.update(transport.responseText);
                    $('aw_giftcard-form').up().insertBefore(
                        container.down(), $('aw_giftcard-form')
                    );
                },
                onComplete: function(transport) {
                    $$('.loader').first().setStyle({zIndex: null}).hide();
                }
            });
            return false;
        }
    </script>
</div>