<?php
/**
 * aheadWorks Co.
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the EULA
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://ecommerce.aheadworks.com/AW-LICENSE.txt
 *
 * =================================================================
 *                 MAGENTO EDITION USAGE NOTICE
 * =================================================================
 * This software is designed to work with Magento community edition and
 * its use on an edition other than specified is prohibited. aheadWorks does not
 * provide extension support in case of incorrect edition use.
 * =================================================================
 *
 * @category   AW
 * @package    AW_Giftcard
 * @version    1.0.9
 * @copyright  Copyright (c) 2010-2012 aheadWorks Co. (http://www.aheadworks.com)
 * @license    http://ecommerce.aheadworks.com/AW-LICENSE.txt
 */
?><?php
$_product = $this->getProduct();
$_id = $_product->getId();
$preConfiguredValues = $this->getPreConfiguredValues();
?>

<div class="form__field aw-gc-form">
<?php if ($_product->isSaleable() && $this->hasAmountOptions()): ?>
    <?php if (!$_product->getAwGcAllowOpenAmount() && (count($this->getAmountOptions()) == 1)): ?>
        <?php $_amount = $this->getAmountOptions(); $_amount = array_shift($_amount); ?>
        <script type="text/javascript">
            //<![CDATA[
            optionsPrice.productPrice = "<?php echo $_amount;?>";
            //]]>
        </script>
    <?php else: ?>
        <div class="form__field aw-gc-amount-form">

            <div class="form__field form__field--required">
                <?php if (count($this->getAmountOptions()) > 0): ?>
                    <label for="aw-gc-amount" id="aw-gc-amount-label-select" class="form__label form__label--required">
                        <?php echo $this->__('Amount');?>
                    </label>
                <?php endif; ?>

                <?php if ($_product->getAwGcAllowOpenAmount()): ?>
                    <label for="aw-gc-custom-amount" id="aw-gc-custom-amount-label-input" class="form__label form__label--required">
                        <?php echo $this->__('Amount in %s', $this->getCurrentCurrency()); ?>
                    </label>
                    <div id="aw-gc-amount-box" class="form__field">
                        <input type="text" id="aw-gc-custom-amount" value="<?php echo $this->escapeHtml($preConfiguredValues->getData('aw_gc_custom_amount')) ?>" name="aw_gc_custom_amount" class="validate-number required-entry form__textfield textfield aw-gc-amount-entry aw-gc-min-amount aw-gc-max-amount" />
                        <?php if ($_product->getAwGcOpenAmountMin() || $_product->getAwGcOpenAmountMax()): ?>
                            <?php $_minAmount = Mage::helper('core')->currency($_product->getAwGcOpenAmountMin(), true, false); ?>
                            <?php $_maxAmount = Mage::helper('core')->currency($_product->getAwGcOpenAmountMax(), true, false); ?>
                            <p class="notice">
                                <?php if ($_product->getAwGcOpenAmountMin()): ?>
                                    <span>
                                        <?php echo $this->__('Minimum: %s', $_minAmount); ?>
                                    </span>
                                <?php endif; ?>

                                <?php if ($_product->getAwGcOpenAmountMax()): ?>
                                    <span>
                                        <?php echo $this->__('Maximum: %s', $_maxAmount); ?>
                                    </span>
                                <?php endif; ?>
                            </p>
                            <script type="text/javascript">
                                //<![CDATA[
                                var minAllowedAmount = <?php echo Mage::helper('core')->currency($_product->getAwGcOpenAmountMin(), false, false) ?>;
                                var maxAllowedAmount = <?php echo Mage::helper('core')->currency($_product->getAwGcOpenAmountMax(), false, false) ?>;

                                function parsePrice(value) {
                                    value = value.replace('\'', '').replace(' ', '');
                                    var separatorComa = value.indexOf(',');
                                    var separatorDot  = value.indexOf('.');

                                    if (separatorComa != -1 && separatorDot != -1) {
                                        if (separatorComa > separatorDot) {
                                            value = value.replace('.', '').replace(',', '.');
                                        } else {
                                            value = value.replace(',', '');
                                        }
                                    } else if (separatorComa != -1) {
                                        value = value.replace(',', '.');
                                    }
                                    return parseFloat(value);
                                }

                                Validation.add('aw-gc-min-amount', <?php echo Zend_Json::encode($this->__('Entered amount is too low')); ?>, function(v) {
                                    return (parsePrice(v) >= minAllowedAmount);
                                });
                                Validation.add('aw-gc-max-amount', <?php echo Zend_Json::encode($this->__('Entered amount is too high')); ?>, function(v) {
                                    if (maxAllowedAmount == 0) {return true;}
                                    return (parsePrice(v) <= maxAllowedAmount);
                                });
                                //]]>
                            </script>
                        <?php endif; ?>
                    </div>
                <?php endif; ?>
                <?php if (count($this->getAmountOptions()) > 0): ?>
                    <?php $configValue = $preConfiguredValues->getData('aw_gc_amounts');?>
                    <p class="form__field form__field--required">
                        <select name="aw_gc_amount" id="aw-gc-amount" class="form__select validate-select required-entry aw-gc-amount-entry">
                            <option value="">
                                <?php echo $this->__('Choose an Amount...') ?>
                            </option>

                            <?php foreach ($this->getAmountOptions() as $value): ?>
                                <option value="<?php echo $value; ?>" <?php echo (($configValue == $value) ? 'selected' : '')?>>
                                    <?php echo Mage::helper('core')->currency($value, true, false); ?>
                                </option>
                            <?php endforeach; ?>

                            <?php if ($_product->getAwGcAllowOpenAmount()): ?>
                                <option value="custom" <?php echo (($configValue == 'custom') ? 'selected' : '')?>>
                                    <?php echo $this->__('Other Amount...') ?>
                                </option>
                            <?php endif; ?>
                        </select>
                    </p>
                <?php endif; ?>
            </div>
        </div>
        <script type="text/javascript">
            //<![CDATA[
            if ($('aw-gc-amount') && $('aw-gc-custom-amount')) {
                $('aw-gc-custom-amount').hide();
                $('aw-gc-amount-box').hide();
                $('aw-gc-custom-amount-label-input').hide();
                Event.observe($('aw-gc-amount'), 'change', switchGiftCardInputs);
            }

            function switchGiftCardInputs()
            {
                if (!$('aw-gc-amount') || !$('aw-gc-custom-amount')) {
                    return;
                }

                var value = $('aw-gc-amount').options[$('aw-gc-amount').selectedIndex].value;
                if (value == 'custom') {
                    $('aw-gc-custom-amount').show();
                    $('aw-gc-amount-box').show();

                    $('aw-gc-amount-label-select').hide();
                    $('aw-gc-custom-amount-label-input').show();
                } else {
                    $('aw-gc-custom-amount').hide();
                    $('aw-gc-amount-box').hide();

                    $('aw-gc-amount-label-select').show();
                    $('aw-gc-custom-amount-label-input').hide();
                }
            }
            switchGiftCardInputs();
            //]]>
        </script>
    <?php endif; ?>
    <div class="form__field aw-gc-send-form">
        <p class="form__field form__field--required">
            <label for="aw-gc-sender-name" class="form__label form__label--required"><?php echo $this->__('Sender Name'); ?></label>
            <?php $senderName = $preConfiguredValues->getData('aw_gc_sender_name') ? $preConfiguredValues->getData('aw_gc_sender_name') : $this->getCustomerName();?>
            <input type="text" id="aw-gc-sender-name" name="aw_gc_sender_name" class="required-entry form__textfield textfield" value="<?php echo $this->escapeHtml($senderName); ?>" />
        </p>
        <?php if ($this->isAllowEmail()): ?>
            <p class="form__field form__field--required">
                <label for="aw-gc-sender-email" class="form__label form__label--required"><?php echo $this->__('Sender Email'); ?></label>
                <?php $senderEmail = $preConfiguredValues->getData('aw_gc_sender_email') ? $preConfiguredValues->getData('aw_gc_sender_email') : $this->getCustomerEmail();?>
                <input type="email" id="aw-gc-sender-email" name="aw_gc_sender_email" class="validate-email required-entry form__textfield textfield" value="<?php echo $this->escapeHtml($senderEmail);?>"/>
            </p>
        <?php endif; ?>
        <p class="form__field form__field--required">
            <label for="aw-gc-recipient-name" class="form__label form__label--required"><?php echo $this->__('Recipient Name'); ?></label>
            <input type="text" id="aw-gc-recipient-name" name="aw_gc_recipient_name" class="required-entry form__textfield textfield" value="<?php echo $this->escapeHtml($preConfiguredValues->getData('aw_gc_recipient_name')) ?>" />
        </p>
        <?php if ($this->isAllowEmail()): ?>
            <label for="aw-gc-recipient-email" class="form__label form__label--required"><?php echo $this->__('Recipient Email'); ?></label>
            <input type="email" id="aw-gc-recipient-email" name="aw_gc_recipient_email" class="validate-email required-entry form__textfield textfield" value="<?php echo $this->escapeHtml($preConfiguredValues->getData('aw_gc_recipient_email')) ?>" />
        <?php endif; ?>
        <?php if ($this->isAllowMessage()): ?>
            <p class="form__field">
                <label for="aw-gc-message" class="form__label"><?php echo $this->__('Message'); ?></label>
                <textarea name="aw_gc_message" id="aw-gc-message" class="form__textfield textfield giftcard-message-max-length" cols="5" rows="3"><?php echo $this->escapeHtml($preConfiguredValues->getData('aw_gc_message')) ?></textarea>
            </p>
        <?php endif; ?>
    </div>
<?php endif; ?>
</div>